#!/bin/bash
# Copy cluster cml output to local cml output

# path to cluster output
PRO=wcrlcluster.csee.wvu.edu:/home/tferrett/cml/output

# path to local output
PLO=/home/tferrett/cml

# copy
scp -r $PRO $PLO
